// Regenerated by `nango deploy` / `nango dryrun` from nango.yaml.
// Checked in so a fresh clone type-checks before the first deploy.
export interface StripeCustomer {
  id: string;
  email: string;
  name: string;
}

export interface XeroInvoice {
  id: string;
  number: string;
  total: number;
  status: string;
}

export interface HubSpotContact {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
}
